- name: set enviroment
  hosts: cuju
  become: yes       # like sudo
  tags: enviroment
  tasks:
    - name: "let {{ ansible_ssh_user }} sudo without password on Ubuntu"      
      lineinfile:       # add a line to a file if it does not exist, after validate.
        path: /etc/sudoers
        line: '{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: install image and headers of linux 4.15.0-29-generic
      apt:        # like apt-get
        pkg:
          - linux-image-4.15.0-29-generic
          - linux-headers-4.15.0-29-generic
        update_cache: yes       # like apt-get update
      when: Ubuntu_version == 18

    - name: update GRUB_DEFAULT
      lineinfile:       # this module will search a file for a line, and ensure that it is present or absent. And this is primarily useful when you want to change a single line in a file only.
        path: /etc/default/grub
        regexp: '^GRUB_DEFAULT='
        line: 'GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 4.15.0-29-generic"'
        owner: root
        group: root
        mode: 0755

    - name: update grub
      command: update-grub        # like type command on shell

    - name: install cuju required package
      apt:
        pkg:
         - vim
         - gcc
         - make
         - gdb
         - fakeroot
         - build-essential
         - kernel-package
         - libncurses5
         - libncurses5-dev
         - zlib1g-dev
         - libglib2.0-dev
         - qemu
         - xorg
         - bridge-utils
         - openvpn
         - libelf-dev
         - libssl-dev
         - libpixman-1-dev
         - nfs-common
         - git
         - tigervnc-viewer
         - expect
        update_cache: yes

    - name: backup old network config
      copy:
        src: /etc/netplan/50-cloud-init.yaml
        dest: /etc/netplan/50-cloud-init.yaml.backup
        remote_src: yes

    - name: copy network.py
      copy:
        src: reset_network_with_bridge.py
        dest: /etc/netplan/reset_network_with_bridge.py
        mode: '0744'

    - name: change primary network config
      command: "python reset_network_with_bridge.py {{ primary_host_nic }} {{ ansible_ssh_host[ansible_ssh_host|length-1] }}"
      args:
        chdir: /etc/netplan
      when: ansible_ssh_host == primary_host_ip

    - name: change backup network config
      command: "python reset_network_with_bridge.py {{ backup_host_nic }} {{ ansible_ssh_host[ansible_ssh_host|length-1] }}"
      args:
        chdir: /etc/netplan
      when: ansible_ssh_host == backup_host_ip

    - name: reboot
      reboot:       # reboot the node and wait 30s, then try to connection with the node. If not successful in 5s, break and try again. If still fail after 600s, return fail.
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30

- name: download and make cuju
  hosts: primary_host
  become: yes
  tasks:

    - name: creat directory /mnt/nfs
      file:       # creat a directory with path and access permissions is 755
        path: /mnt/nfs
        state: directory
        mode: 0755

    - name: mount remote nfsfolder to remote /mnt/nfs
      mount:        # This module controls active and configured mount points in /etc/fstab .
        path: /mnt/nfs
        src: "{{ local_host_ip }}:{{ nfs_folder_path }}"
        fstype: nfs
        state: mounted

    - name: git clone cuju
      command: git clone https://github.com/Cuju-ft/Cuju.git
      args:
        chdir: /mnt/nfs

    - name: Cuju change version to Ubuntu18
      command: git checkout support/kernel4.15
      args:
        chdir: /mnt/nfs/Cuju        # path
      when: Ubuntu_version == 18

    - name: Cuju make
      command: "{{ item }}"       # execute command in order.
      with_items:
        - ./configure --enable-cuju --enable-kvm --disable-pie --target-list=x86_64-softmmu
        - make clean
        - make -j8
      args:
        chdir: /mnt/nfs/Cuju        # path

    - name: KVM make
      command: "{{ item }}"
      with_items:
        - ./configure
        - make clean
        - make -j8
        - ./reinsmodkvm.sh
      args:
        chdir: /mnt/nfs/Cuju/kvm

    - name: copy runvm.sh, recv.sh, ftmode.sh
      copy:         # the copy module copies a file from the local or remote machine to a location on the remote machine.
        src: "{{ item }}"
        dest: /mnt/nfs/Cuju
        mode: 0755
      with_items:
        - ./cuju_sh/runvm.sh
        - ./cuju_sh/recv.sh
        - ./cuju_sh/ftmode.sh

    - name: change ftmode.sh
      replace:
        path: /mnt/nfs/Cuju/ftmode.sh
        regexp: '\[backup address\]'
        replace: '{{ backup_host_ip }}'

    - name: download gdown.pl (download Ubuntu20G-1604.img)
      get_url:        # downloads files from HTTP, HTTPS, or FTP to the remote server. The remote server must have direct access to the remote resource.
        url: https://raw.githubusercontent.com/circulosmeos/gdown.pl/master/gdown.pl
        dest: /mnt/nfs
        mode: 0775

    - name: download Ubuntu20G-1604.tar.gz (download Ubuntu20G-1604.img)
      command: ./gdown.pl https://drive.google.com/file/d/0B9au9R9FzSWKNjZpWUNlNDZLcEU/view Ubuntu20G-1604.tar.gz
      args:
        chdir: /mnt/nfs

    - name: unzip Ubuntu20G-1604.tar.gz (download Ubuntu20G-1604.img)
      unarchive:        # this module unpacks an archive. It will not unpack a compressed file that does not contain an archive.
        src: /mnt/nfs/Ubuntu20G-1604.tar.gz
        dest: /mnt/nfs
        remote_src: yes

- name: mount guset raw image
  hosts: primary_host
  become: yes
  tasks:

    - name: install kpartx
      apt:
        pkg:
         - kpartx
        update_cache: yes

    - name: creat directory /mnt/vm
      file:       # creat a directory with path and access permissions is 755
        path: /mnt/vm
        state: directory
        mode: 0755

    - name: lookup whick /dev/loop can use
      command: losetup -f
      register: dev_loop

    - name: add to loop and partation
      command: "{{ item }}"
      with_items:
        - losetup -f /mnt/nfs/Ubuntu20G-1604.img 
        - "kpartx -a {{ dev_loop['stdout'] }}"
    
    - name: find partation map
      command: "kpartx -l {{ dev_loop['stdout'] }}"
      register: loop_part

    - name: mount
      command: "mount /dev/mapper/{{ loop_part['stdout'].split(' ')[0] }} /mnt/vm"

- name: change guest network
  hosts: primary_host
  become: yes
  tasks:

    - name: change address
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^address.*'
        line: "address {{ guest_ip }}"

    - name: change netmask
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^netmask.*'
        line: "netmask {{ guset_netmask }}"

    - name: change network
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^network.*'
        line: "network {{ guest_network }}"

    - name: change broadcast
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^broadcast.*'
        line: "broadcast {{ guest_broadcast }}"

    - name: change gateway
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^gateway.*'
        line: "gateway {{ guest_gateway }}"

    - name: change dns-nameservers
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^dns-nameservers.*'
        line: "dns-nameservers {{ guest_dns_nameservers }}"

- name: unmount guest raw image
  hosts: primary_host
  become: yes
  tasks:

    - name: unmount guest image
      command: "{{ item }}"
      with_items:
        - umount /mnt/vm
        - sync
        - "kpartx -d {{ dev_loop['stdout'] }}"
        - sync
        - "losetup -d {{ dev_loop['stdout'] }}"
        - sync
        - rm -r /mnt/vm
