- name: deployment cuju
  hosts: cuju
  vars:
    - install_machine_username: "user"
    - install_machine_ip_address: "192.168.77.151"
    - nfs_folder_path: "~"        # remote
  tasks:
    - name: "let {{ install_machine_username }} sudo without password on Ubuntu"
      become: yes       # like sudo
      lineinfile:       # add a line to a file if it does not exist, after validate.
        path: /etc/sudoers
        line: '{{ install_machine_username }} ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: install image and headers of linux 4.15.0-29-generic
      become: yes
      apt:        # like apt-get
        pkg:
          - linux-image-4.15.0-29-generic
          - linux-headers-4.15.0-29-generic
        update_cache: yes       # like apt-get update

    - name: update GRUB_DEFAULT
      become: yes
      lineinfile:       # this module will search a file for a line, and ensure that it is present or absent. And this is primarily useful when you want to change a single line in a file only.
        path: /etc/default/grub
        regexp: '^GRUB_DEFAULT='
        line: 'GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 4.15.0-29-generic"'
        owner: root
        group: root
        mode: 0755

    - name: update grub
      become: yes
      command: update-grub        # like type command on shell

    - name: reboot
      become: yes
      reboot:       # reboot the node and wait 30s, then try to connection with the node. If not successful in 5s, break and try again. If still fail after 600s, return fail.
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30

    - name: install cuju required package
      become: yes
      apt:
        pkg:
         - vim
         - gcc
         - make
         - gdb
         - fakeroot
         - build-essential
         - kernel-package
         - libncurses5
         - libncurses5-dev
         - zlib1g-dev
         - libglib2.0-dev
         - qemu
         - xorg
         - bridge-utils
         - openvpn
         - libelf-dev
         - libssl-dev
         - libpixman-1-dev
         - nfs-common
         - git
         - tigervnc-viewer
         - nfs-kernel-server
        update_cache: yes

    - name: creat directory /mnt/nfs
      become: yes
      file:       # creat a directory with path and access permissions is 755
        path: /mnt/nfs
        state: directory
        mode: 0755

    - name: creat directory nfsfolder
      file:
        path: "{{ nfs_folder_path }}/nfsfolder"
        state: directory
        mode: 0755

    - name: add line to /etc/exports
      become: yes
      lineinfile:
        path: /etc/exports
        regexp: "^/home/{{ install_machine_username }}/nfsfolder *(rw,no_root_squash,no_subtree_check)"
        line: "/home/{{ install_machine_username }}/nfsfolder *(rw,no_root_squash,no_subtree_check)"

    - name: restart nfs kernel server
      become: yes
      command: /etc/init.d/nfs-kernel-server restart

    - name: mount remote nfsfolder to remote /mnt/nfs
      become: yes
      mount:        # This module controls active and configured mount points in /etc/fstab .
        path: /mnt/nfs
        src: "{{ install_machine_ip_address }}:/home/{{install_machine_username }}/nfsfolder"
        fstype: nfs
        state: mounted

    - name: git clone cuju
      command: git clone https://github.com/Cuju-ft/Cuju.git
      args:
        chdir: /mnt/nfs

    - name: Cuju make
      command: "{{ item }}"       # execute command in order.
      with_items:
        - git checkout support/kernel4.15
        - ./configure --enable-cuju --enable-kvm --disable-pie --target-list=x86_64-softmmu
        - make clean
        - make -j8
      args:
        chdir: /mnt/nfs/Cuju        # path

    - name: KVM make
      command: "{{ item }}"
      with_items:
        - ./configure
        - make clean
        - make -j8
        - ./reinsmodkvm.sh
      args:
        chdir: /mnt/nfs/Cuju/kvm

    - name: copy runvm.sh, recv.sh, ftmode.sh
      copy:         # the copy module copies a file from the local or remote machine to a location on the remote machine.
        src: "{{ item }}"
        dest: /mnt/nfs/Cuju
        mode: 0755
      with_items:
        - ./cuju_sh/runvm.sh
        - ./cuju_sh/recv.sh
        - ./cuju_sh/ftmode.sh

    - name: change runvm.sh
      replace:        # This module will replace all instances of a pattern within a file.
        path: /mnt/nfs/Cuju/runvm.sh
        regexp: '\[your username\]'
        replace: "{{ install_machine_username }}"

    - name: change ftmode.sh
      replace:
        path: /mnt/nfs/Cuju/ftmode.sh
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      with_items:
          - { regexp: '\[your username\]', replace: '{{ install_machine_username }}' }
          - { regexp: '\[your address\]', replace: '{{ install_machine_ip_address }}' }

    - name: download gdown.pl (download Ubuntu20G-1604.img)
      get_url:        # downloads files from HTTP, HTTPS, or FTP to the remote server. The remote server must have direct access to the remote resource.
        url: https://raw.githubusercontent.com/circulosmeos/gdown.pl/master/gdown.pl
        dest: /mnt/nfs
        mode: 0775

    - name: download Ubuntu20G-1604.tar.gz (download Ubuntu20G-1604.img)
      command: ./gdown.pl https://drive.google.com/file/d/0B9au9R9FzSWKNjZpWUNlNDZLcEU/view Ubuntu20G-1604.tar.gz
      args:
        chdir: /mnt/nfs

    - name: unzip Ubuntu20G-1604.tar.gz (download Ubuntu20G-1604.img)
      unarchive:        # this module unpacks an archive. It will not unpack a compressed file that does not contain an archive.
        src: /mnt/nfs/Ubuntu20G-1604.tar.gz
        dest: /mnt/nfs
        remote_src: yes
