- name: mount with nfs
  hosts: cuju
  tasks:
    - name: creat directory with share disk path
      become: yes
      file:       # creat a directory with path and access permissions is 755
        path: "{{ share_disk_path }}"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 0755

    - name: mount local share disk to remote host
      become: yes
      mount:
        path: "{{ share_disk_path }}"
        src: "{{ local_host_ip }}:{{ nfs_folder_path }}"
        fstype: nfs
        state: mounted
