- name: mount guset raw image
  hosts: primary_host
  become: yes
  tasks:

    - name: install kpartx
      apt:
        pkg:
         - kpartx
        update_cache: yes

    - name: creat directory /mnt/vm
      file:       # creat a directory with path and access permissions is 755
        path: /mnt/vm
        state: directory
        mode: 0755

    - name: lookup whick /dev/loop can use
      command: losetup -f
      register: dev_loop

    - name: add to loop and partation
      command: "{{ item }}"
      with_items:
        - "losetup -f {{ share_disk_path }}/Ubuntu20G-1604.img"
        - "kpartx -a {{ dev_loop['stdout'] }}"
    
    - name: find partation map
      command: "kpartx -l {{ dev_loop['stdout'] }}"
      register: loop_part

    - name: mount
      command: "mount /dev/mapper/{{ loop_part['stdout'].split(' ')[0] }} /mnt/vm"

- name: change guest network
  hosts: primary_host
  become: yes
  tasks:

    - name: change address
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^address.*'
        line: "address {{ guest_ip }}"

    - name: change netmask
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^netmask.*'
        line: "netmask {{ guset_netmask }}"

    - name: change network
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^network.*'
        line: "network {{ guest_network }}"

    - name: change broadcast
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^broadcast.*'
        line: "broadcast {{ guest_broadcast }}"

    - name: change gateway
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^gateway.*'
        line: "gateway {{ guest_gateway }}"

    - name: change dns-nameservers
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^dns-nameservers.*'
        line: "dns-nameservers {{ guest_dns_nameservers }}"

- name: unmount guest raw image
  hosts: primary_host
  become: yes
  tasks:

    - name: unmount /mnt/vm
      mount:
        path: /mnt/vm
        state: unmounted

    - name: remove /mnt/vm
      file:
        path: /mnt/vm
        state: absent

    - name: delete device loop
      command: "{{ item }}"
      with_items:
        - sync
        - "kpartx -d {{ dev_loop['stdout'] }}"
        - sync
        - "losetup -d {{ dev_loop['stdout'] }}"
