- name: mount guset raw image
  hosts: primary_host
  tasks:

    - name: install kpartx
      become: yes
      apt:
        pkg:
         - kpartx
        update_cache: yes

    - name: creat /mnt/vm
      become: yes
      file:       # creat a directory with path and access permissions is 755
        path: /mnt/vm
        state: directory
        mode: 0755

    - name: lookup whick /dev/loop can use
      become: yes
      command: losetup -f
      register: dev_loop

    - name: add to loop and partation
      become: yes
      command: "{{ item }}"
      with_items:
        - losetup -f /mnt/nfs/Ubuntu20G-1604.img 
        - "kpartx -a {{ dev_loop['stdout'] }}"
    
    - name: find partation map
      become: yes
      command: "kpartx -l {{ dev_loop['stdout'] }}"
      register: loop_part

    - name: mount
      become: yes
      command: "mount /dev/mapper/{{ loop_part['stdout'].split(' ')[0] }} /mnt/vm"

- name: change guest network
  hosts: primary_host
  become: yes
  tasks:

    - name: address
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^address.*'
        line: "address {{ guest_ip }}"

    - name: netmask
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^netmask.*'
        line: "netmask {{ guset_netmask }}"

    - name: network
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^network.*'
        line: "network {{ guest_network }}"

    - name: broadcast
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^broadcast.*'
        line: "broadcast {{ guest_broadcast }}"

    - name: gateway
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^gateway.*'
        line: "gateway {{ guest_gateway }}"

    - name: dns-nameservers
      lineinfile:
        path: /mnt/vm/etc/network/interfaces
        regexp: '^dns-nameservers.*'
        line: "dns-nameservers {{ guest_dns_nameservers }}"

- name: unmount guest raw image
  hosts: primary_host
  become: yes
  tasks:

    - name: unmount /mnt/vm
      command: "{{ item }}"
      with_items:
        - umount /mnt/vm
        - sync
        - "kpartx -d {{ dev_loop['stdout'] }}"
        - sync
        - "losetup -d {{ dev_loop['stdout'] }}"
        - sync
        - rm -r /mnt/vm

    
